# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'RevolutTestApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
# Networking
  pod 'Alamofire', '~> 4.0'
  #pod 'AlamofireImage', '~> 3.4.1'


# UI
  pod 'IQKeyboardManagerSwift'

  #
  pod 'Reusable'
  pod 'SwiftGen'

end
